name: Dependabot Automerge
on: pull_request
jobs:
  worker:
    runs-on: ubuntu-latest
    services:
      devnet:
        image: shardlabs/starknet-devnet:latest-seed0
        ports:
          - 5050:5050
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn setup
      - name: Install Playwright Browsers
        run: npx playwright install chromium
      - run: yarn build
      - run: yarn test
      - run: xvfb-run --auto-servernum yarn test:e2e
      - run: yarn --cwd packages/dapp export
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |-
            await github.rest.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            await exec.exec("sleep 2")
            await github.rest.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash'
            })
